### ISSUE TITLE
TCP receive timeout

### ISSUE THREAD

**Issue by dieris** [BBN-Q/libaps2#63] opened 2016-05-10 13:07 UTC
Repeated 2D sweep abruptly stops in the middle of a sweep after 1 to 10 hours of acquisition. Example: taking GST single shots (segments: ~28k, repeat = 50/file). The error occurs within one of the files (at the start of any repeat number). 

Matlab error:

`APS2 library call failed with message: Timed out while waiting to receive data.`

libaps2 log:

`ERROR: TCP receive timed out!`

Need to stop Matlab processes from task manager in order to restore the communication.

**Comment by caryan** [comment] 2016-05-10 15:40
Hmm, that's going to be annoying to debug.  Is there any way to decrease the number of round robins and get it to fail faster?

**Comment by dieris** [comment] 2016-05-10 15:41
I'm can try to reduce the number of segments so that it loops faster (they are already single shots)

**Comment by dieris** [comment] 2016-05-12 12:58
new occurrence, now at the start of a pulse calibration sequence (after ~2 hours of loop)

**Comment by caryan** [comment] 2016-05-13 15:00
@dieris commit 1993efca03286c699d40fed1cc6316771c47f455 won't fix the time out but should help with Matlab hangs.

**Comment by dieris** [comment] 2016-06-07 21:16
Matlab still hangs when time out occurs. Need to close Matlab and end the process

**Comment by blakejohnson** [comment] 2016-07-20 21:10
It seems like we need to do something to improve the robustness of the TCP stream. For instance, if the client PC network cable is unplugged, that will leave the TCP session open on the APS2 and no one else will be able to connect to it. One possible fix is to have the client send a heartbeat every second, and close the session on the APS2 if no heartbeat is received in ~10 seconds.

**Comment by blakejohnson** [comment] 2016-08-08 20:59
#78 is essentially a duplicate of this problem. @caryan and I believe we have solved it.

**Closed by blakejohnson** 2016-08-08 20:59 UTC
Labels: bug
